### ISSUE TITLE
JSON recipe loading crashing on world startup

### ISSUE THREAD

**Issue by Mortvana** [MachineMuse/Numina#11]
As the title states.
https://gist.github.com/Mortvana/7d70de380b517114e41c

**Comment by Hanse00** [comment]
I'm having the exact same issue, it may be worth mentioning that it happens at the exact moment the server goes from generating world, to actually being ready to join. Both on a single player world, and a dedicated server.

**Comment by rob5251** [comment]
As Hanse said, it seems to happen as soon as the world is loading in.
Here is a crash report:
http://paste.ee/p/MV4jf

**Comment by CandiceJoy** [comment]
Same crash.  Metric's fix doesn't help.

**Comment by XFaucheurX** [comment]
Hi all and @MachineMuse,
Any news about this problem ? I have the same crash when using recipes (Vanilla et Thermal).
Thx.

**Comment by MrMetric** [comment]
@CandiceJoy I guess the version changed. I'll fix it later

**Comment by malice936** [comment]
Yep I'm having the same crash on build #100, but I haven't tried the gson fix so I may give that a shot.

**Comment by MCAeolus** [comment]
@MrMetric , I just used your fix for Direwold20 (1.7.10) modpack (to add CustomNPCs,) and it works so I don't know why others are having problems.

**Comment by Andre-Maartens** [comment]
I am also crashing on load of new world
http://pastebin.com/3HgETnRC

**Comment by MachineMuse** [comment]
hello, I know it's been like 4 months but...I finally merged in the QMX changes so please test if this still occurs. Thanks!

**Comment by TerdyTheTerd** [comment]
Thank you for adding that fix, Its confirmed working for me, can finally use Better Storage and Power Suits in my modpack, thanks!!!!

**Comment by MachineMuse** [comment]
great :)
