### ISSUE TITLE
Crash when used U to show recipes

### ISSUE THREAD

**Issue by JasonMcRay** [MachineMuse/Numina#13]
When i hit R to see how to make an item, it works fine.
But if I use U to see what I can do with that item, it crashes with following crash: http://pastebin.com/PKN5Qj21 - Crash occures no matter on which item i click with "U"

I have used custom recipes. When I check if they are working (with R on MPS items) i see them work fine.
Custom Recipes: http://pastebin.com/A9ikwgEa

Its happening only when I have Numina and MPS installed

Also for some reason I am unable to make the recipe Basic/Advanced Plating into GT Steel/Titanium Ingots to work

MC: 1.7.10
Forge: 10.13.2.1232
Numina: 4.0.99
MPS: 0.11.0.175

**Comment by MachineMuse** [comment]
This seems to be fixed with updating the version of NEI.
