### ISSUE TITLE
Mod conflict with Immersive Engineering - crash when pressing "U" to open NEI

### ISSUE THREAD

**Issue by WesCook** [MachineMuse/Numina#16]
Numina seems to be causing NEI to crash when using the "U" functionality.  This is only true under a specific set of circumstances:
1. Numina is loaded.
2. Immersive Engineering is loaded.
3. The Thermal Expansion recipes are in the MPS config folder.  I have not tested other recipe files.

The mods should all be fully updated.  They are as follows:
- ModularPowersuits-0.11.0.283a-RV3.jar
- Numina-0.4.0.131.jar
- ImmersiveEngineering-0.6.0.jar
- NotEnoughItems-1.7.10-1.0.5.118-universal.jar
- CodeChickenCore-1.7.10-1.0.7.47-universal.jar
- CodeChickenLib-1.7.10-1.1.3.138-universal.jar

This crash can be resolved by removing Immersive Engineering, Numina, or the mps-thermalexpansion.recipes file from the configs folder.  MPS does not need to be loaded when these conditions are met - only Numina.

A copy of the crash log is here: http://pastebin.com/x8QNysCx

I hope this helps.  Thank you.

**Comment by Xen1290** [comment]
Try with latest versions of all mods, and reset your machinemuse config folder

**Comment by WesCook** [comment]
Hi Xen,

Using the latest version of each, this issue appears to be resolved.  Thank you.  Players will appreciate being able to craft MPS item again!

**Comment by Xen1290** [comment]
Good ! :+1: 
This can be closed @MachineMuse
