### ISSUE TITLE
useFOVFix with default = true causes other mods to break

### ISSUE THREAD

**Issue by mindforger** [MachineMuse/Numina#17]
Mods like ImmersiveEngineering using the FOV to create a sniper zoom for their weapons

can you provide an API or make this function in any way controllable or make it off by default with a hint to the cross mod interaction?! 
People start hitting other mods Issue tracker with "your zoom does not work" threads

or maybe an idea on how to manipulate zoom without using FOV?!

**Comment by lehjr** [comment]
I'll look into this for 1.9.4, since that's what I'm working on now. Builds for 1.7 and 1.8 will likely not be receiving updates so that I can focus on getting the 1.9.4 in better shape than the 1.8.9 port was.

**Comment by mindforger** [comment]
sure no problem, i was asking because it started popping up since IE for 1.8 and 1.9 introduced zoom mechanic :) 
and i then found several other mods with such issues linking to numina and i thought you might be interested as it s always easy to blame somebody else without telling him that something is bogus

**Comment by lehjr** [comment]
Funny thing is though that the "FOV fix" has been around for almost 3 years and there really hasn't been much that I could find as far as issues reported here or in the MPS repo.

https://github.com/MinecraftForge/MinecraftForge/blob/1.9.4/src/main/java/net/minecraftforge/client/event/FOVUpdateEvent.java

**Comment by lehjr** [comment]
Still though, having the ability to toggle it ingame would probably be useful

**Comment by lehjr** [comment]
For 1.10, players will be able to toggle the "FOV Fix" with a user defined key instead of having a static config setting. I may backport this when I get done porting MPS to 1.10.

**Comment by mindforger** [comment]
thank you sir, very kind :)

**Comment by lehjr** [comment]
Just a heads up. There will be a maintenance release for 1.7.10 where this can be toggled. Kinda late, but the build will be out in a few days.

**Comment by mindforger** [comment]
wohoooo :) i am still mainly playing on 1.7.10, apreciate it
