### ISSUE TITLE
Crash 1.10.2 launch

### ISSUE THREAD

**Issue by NicosaurusRex99** [MachineMuse/Numina#22]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from numina (numina)

Full log @ https://pastebin.com/fb0PDQWH

**Comment by lehjr** [comment]
o.0 Interesting. Thanks for the log.

**Comment by lehjr** [comment]
Gonna test a fix for this in within the next hour.

**Comment by lehjr** [comment]
wait, Numina-0.4.1.104.jar.. that's for 1.7.10. There is no separate build of Numina for 1.10.2 at the moment.

**Comment by lehjr** [comment]
And that's not even the latest build of Numina. Weird. I've removed the "dependency" on Curseforge so that the Numina doesn't get downloaded with MPS. 
1.7.10 builds have been around long enough they should know that they need it.

**Comment by NicosaurusRex99** [comment]
O.o so remove numina and it will work?

**Comment by lehjr** [comment]
yes. Common issue.

**Comment by NicosaurusRex99** [comment]
aight

**Comment by NicosaurusRex99** [comment]
its loading without issues atm

**Comment by dshadowwolf** [comment]
Curse still insists on it for 1.10 if you add via the Curse Client

**Comment by NicosaurusRex99** [comment]
tweet issue to zeldo kavira and zeldo can probs fix it

**Comment by lehjr** [comment]
Unfortunately, I cannot use the curse client to test since I'm a Linux user. Not much more I can do at the moment.

**Comment by NicosaurusRex99** [comment]
@lehjr if i recieve issues ill post on github so i can  help

**Comment by dshadowwolf** [comment]
Seems to have cleared up - I removed MPS and Numina, then reinstalled and Numina did not show up. Looks like it might have been a caching error or I managed to get in just before you changed the deps and got caught by local caching.

**Comment by NicosaurusRex99** [comment]
O.o
