### ISSUE TITLE
Mod not loading 1.12.2 - 0.7.0.029 

### ISSUE THREAD

**Issue by PhilSkinn** [MachineMuse/Numina#25]
![2019-01-23_22 34 46](https://user-images.githubusercontent.com/32152806/51652870-1ff4c580-1f5f-11e9-9bcc-784495a47c73.png)
For some reason, when I went to add this mod into my pack, it refused to load. I looked in the config files and the mod options in-game and it didn't show up at all. I assume this is just an Alpha glitch or something, but I would like some assistance. This is one of my favorite mods, so I was excited to see it update. I can provide a list of the mods in my pack if it'll help but I don't think any of the mods would have compatability issues. I'll try to craft something from the mod in case JEI isn't registering the recipes or something.

**Comment by lehjr** [comment]
Start by looking at the logs.

**Comment by lehjr** [comment]
Also, this is the bug tracker for Numina, not MPS.

**Comment by PhilSkinn** [comment]
Thank you for letting me know, I will move the report over to the MPS github
