### ISSUE TITLE
[1.12.2] Annoying FOV changes

### ISSUE THREAD

**Issue by MusicMaestro123** [MachineMuse/Numina#30]
Perhaps a config option to disable because it makes my FOV go really small!

**Comment by MusicMaestro123** [comment]
I can't even find a config file.

**Comment by lehjr** [comment]
you mean like the config option that's already there plus the keybinding option to toggle it that's already there?

**Comment by MusicMaestro123** [comment]
Wait found it!

**Comment by MusicMaestro123** [comment]
I found it. It doesn't matter.
