### ISSUE TITLE
Numina/ Vics Modern Warfare Mod Compatibility

### ISSUE THREAD

**Issue by PHackersB** [MachineMuse/Numina#38]
Hello Together,
i have a modpack (1.7.10) from a server and nobody on the server can zoom with a gun from Vics Modern Warfare i searched for the mod which has the error and found Numina.
without Numina the modpack works but we need this mod for the server and i dont know how i can fix that.
i think its an problem that Numina has a zoom too and it has a error.
The name of the Modpack is Dynamic Warfare
i hope u can help me

PHackersB

**Comment by lehjr** [comment]
Sorry, but 1.7.10 is so old that the development environment is broken and unsupported. Even if the issue was found, nothing could be done to fix it. I'm not even sure if the development environment would support any modern version of Java.
